/* eslint-disable @typescript-eslint/no-unused-vars */
const SET_PARTICIPANTS_DATA_TYPE = 'Participants/SET_PARTICIPANTS_DATA_TYPE';
const PUSH_NEW_PARTICIPANT_TYPE = 'Participants/PUSH_NEW_PARTICIPANT_TYPE';
const SET_CURRENT_USER_TYPE = 'Participants/SET_CURRENT_USER_TYPE';
const UPDATE_CURRENT_PARTICIPANT_TYPE = 'Participants/UPDATE_CURRENT_PARTICIPANT_TYPE';
const LOGOUT_USER_TYPE = 'Participants/LOGOUT_USER_TYPE';
const SET_LOADING_TYPE = 'Participants/SET_LOADING_TYPE';

export enum PARTICIPANTS_TYPES {
  SET_PARTICIPANTS_DATA_TYPE,
  PUSH_NEW_PARTICIPANT_TYPE,
  SET_CURRENT_USER_TYPE,
  UPDATE_CURRENT_PARTICIPANT_TYPE,
  LOGOUT_USER_TYPE,
  SET_LOADING_TYPE,
}